name: 生成书籍

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 22 * * *' # 6:00,18:00 （GMT+8）
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.1
    - name: 配置环境
      run: |
        sudo apt install libegl1 libopengl0
        sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin
        pip3 install requests
        pip3 install pytz
        pip3 install feedparser
        pip3 install pillow
        pip3 install bs4
        pip3 install oss2
    - name: 执行程序
      run: |
        python3 ./src/genBook.py
      env: 
          config: ${{ secrets.CONFIG }}
    - name: update to repo
      run: |
        git config --global user.name ${{ secrets.GITHUBUSER }}
        git config --global user.email ${{ secrets.GITHUBEMAIL }}
        git add . && echo 添加变动文件
        git commit -m 'update to repo' && echo commit
        git push origin main && echo push!
